language: python

# for container-y goodness:
sudo: false

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"

install:
  - "pip install -Ue .[test,build]"

# command to run tests, e.g. python setup.py test
script: coverage run --timid --source sybil,tests -m py.test

after_success:
  - coveralls

deploy:
  provider: pypi
  user: chrisw
  password:
    secure: p6Cl2uxMjdZRAz8VX+TMSFymCTVnFSA9LycOH9ZUEnbzDtqwnDV8lzZR48NXrMO1xDZ5Q4/qJm2UDh5ulMd60hotXM7IvUBCTQN1z1FwIJwig0xUrz3qKavuYehSsJ0ow+fdFKN1W4Y1wWl9pltuQ9OUUVKFR4AGZ1pdvT56O8+/cwHA/CbEO8LrRnLjoj3xfVoo+v8mUF6Z1ETQ28TV6HbROM6jKCcQ3Ol5IVpxqgbGH5GLeY9zE1Kua9wfkuBKYyIG0wm6iOU4OaXdVOg4X1G1mdECKx6ZCB71kVy6JeimNMBjzbs45zNj/IRxC5cFXNDDKn19HqBC+aQNsMh1+dgwC3LgJXyysVlY+M/Uic4ZsFvsZ3AbDQRVEneivfqh+KMLzY8PoJOgqcx4MNTU4brxuzfiu/KS3IF69xBfXSmsu2UOi/ePFidDHfNhdsa8+NBbYQrJYJIxbIm/YPE/prDVqR3eAsQZBtyE+6yTecvmqu1mmyYjvzcrQ27/n1NS/L1g6I8BZjRFws4WlSiMlVbVV9QBl/AhICwpJZHxateM7/kf+bbEGVacV/VWn9sIDOl6jMAE0IeN2gLdTO+Dj2z8tyV6c8tMFH1JeZ31CGN67oO4kb397kfDN14o7KNfFb+wxOHOzOZYwfvMYjLoPD5AdMsPbm4inpVooN5irhU=
  on:
    tags: true
    repo: cjw296/sybil
    python: "3.6"
  skip_cleanup: true
  distributions: "sdist bdist_wheel"
